# Numero de condición

In [3]:
import numpy as np
a = np.array([[1,1/2,1/3],[1/2,1/3,1/4],[1/3,1/4,1/5]], float)
b = np.array([[10],[20],[30]])
s = np.linalg.solve(a,b)
print(s)

[[  270.]
 [-1920.]
 [ 2100.]]


In [4]:
n = np.linalg.norm(a, np.inf)
print(n)

1.8333333333333333


In [6]:
d = np.linalg.inv(a)
print(d)

[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]


In [8]:
c = np.linalg.cond(a, np.inf)
print(c)

748.0000000000028


In [11]:
e = np.linalg.norm(a, np.inf) * np.linalg.norm(d, np.inf)
print(e)

748.0000000000028
